version: "3.9"

services:
  tokenizer:
    container_name: tokenizer
    restart: unless-stopped
    image: ghcr.io/bookpanda/lyrics2anki-tokenizer
    ports:
      - 8080:8080
    environment:
      - FLASK_APP=app.py
      - API_KEY=8080
 